#!/usr/bin/env bash

#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #

# Script resets global settings

rm -rf settings/global
touch settings/global
echo "#!/usr/bin/env bash" >> settings/global
echo "" >> settings/global
echo "###################################################################" >> settings/global
echo "#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #" >> settings/global
echo "###################################################################" >> settings/global
echo "" >> settings/global
echo "###################################################################" >> settings/global
echo "# XCPEDIR stores a path to the top-level directory containing all" >> settings/global
echo "# of the ingredients necessary to configure and execute functional" >> settings/global
echo "# connectivity pipelines using the XCP Engine." >> settings/global
echo "XCPEDIR=$(pwd)" >> settings/global
echo "###################################################################" >> settings/global
echo "" >> settings/global
echo "###################################################################" >> settings/global
echo "# RPATH stores a path to the local installation of R. Dependencies" >> settings/global
echo "# may include:" >> settings/global
echo "#  * ANTsR" >> settings/global
echo "#  * pracma" >> settings/global
echo "#  * igraph" >> settings/global
echo "#  * signal" >> settings/global
echo "#  * optparse" >> settings/global
echo "RPATH=$(which R)" >> settings/global
echo "###################################################################" >> settings/global
echo "" >> settings/global
echo "###################################################################" >> settings/global
echo "# FSLDIR stores a path to the local installation of FSL." >> settings/global
echo "FSLDIR=$(echo $FSLDIR)" >> settings/global
echo "###################################################################" >> settings/global
echo "" >> settings/global
echo "###################################################################" >> settings/global
echo "# ANTSPATH stores a path to the local installation of ANTs." >> settings/global
echo "ANTSPATH=$(echo $ANTSPATH)" >> settings/global
echo "###################################################################" >> settings/global
echo "" >> settings/global
echo "###################################################################" >> settings/global
echo "# When subject-specific paths are generalised by utils/genpath," >> settings/global
echo "# the value of KEEPNUM determines whether leading numeric values" >> settings/global
echo "# not matching subject identifiers are retained." >> settings/global
echo "KEEPNUM=1" >> settings/global
echo "###################################################################" >> settings/global
echo "" >> settings/global
echo "###################################################################" >> settings/global
echo "# The default value of the starting directory is stored here." >> settings/global
echo "# Editing this will change where the XCP configuration script" >> settings/global
echo "# searches by default." >> settings/global
echo "startdir=$(pwd)" >> settings/global
echo "###################################################################" >> settings/global
echo "" >> settings/global
echo "###################################################################" >> settings/global
echo "# Outputs of modules may be prepended with an integer indicating" >> settings/global
echo "# their context in the pipeline. Set NUMOUT to 1 to enable this." >> settings/global
echo "NUMOUT=0" >> settings/global
echo "###################################################################" >> settings/global
echo "" >> settings/global
echo "###################################################################" >> settings/global
echo "# Design files and analysis names will be timestamped to the" >> settings/global
echo "# minute if TIMESTAMP is set to 1." >> settings/global
echo "TIMESTAMP=1" >> settings/global
echo "###################################################################" >> settings/global
echo "" >> settings/global
echo "###################################################################" >> settings/global
echo "# The default pipeline is stored here. Edit this to change the" >> settings/global
echo "# default pipeline." >> settings/global
echo "pipeline=" >> settings/global
echo "###################################################################" >> settings/global
chmod 755 settings/global
