#!/usr/bin/env bash

###################################################################
#  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  #
###################################################################

###################################################################
# Script resets global settings
###################################################################

###################################################################
#    ⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗      #
# Check for existence of all global variables
###################################################################
exitFlag=0
envVars="
         XCPEDIR
         FSLDIR
         AFNI_PATH
         C3D_PATH
         ANTSPATH
        "
for v in ${envVars}
   do
   if [[ -z ${!v} ]]
      then
      setVars="${setVars} ${v}"
      exitFlag=2
   fi
done
if (( ${exitFlag} > 0 ))
   then 
   dirVal=$(dirname $0)
   pushd ${dirVal} >>/dev/null
   dirVal=$(pwd)
   echo \
   "
   WARNING: GLOBAL VARIABLES NOT RESET.
   
   The following environmental variables are undefined:
   
   ${setVars}
   
   These variables must be defined in order to enable
   XCP functionality. Undefined variables may be reflective
   of uninstalled prerequisites or of missing definitions,
   for instance in ~/.bash_profile
   
   Please ensure that these variables are defined in
   accordance with the provided example:
   export XCPEDIR=${dirVal}
   "
   exit 2
fi

which R >/dev/null 2>&1
if (( $? > 0 ))
   then 
   echo \
   "
   WARNING: GLOBAL VARIABLES NOT RESET.
   
   R is not currently in $USER's "'$PATH'"
   
   R must be in the "'$PATH'" in order to enable XCP
   functionality.
   
   Please ensure that R is installed and can be executed
   from the command line.
   "
   exit 2
fi

if [[ -z ${JQ_PATH} ]]
   then
   if [[ $(arch) == x86_64 ]]
      then
      export JQ_PATH=${XCPEDIR}/thirdparty/jq/jq-linux64
   else
      export JQ_PATH=${XCPEDIR}/thirdparty/jq/jq-linux32
   fi
fi

###################################################################
# Done checking for variables
#    ⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗⊗      #
###################################################################


###################################################################
# Write to the global variables file.
###################################################################
rm -rf ${XCPEDIR}/core/global
echo \
"#!/usr/bin/env bash

###################################################################
#  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  #
###################################################################

###################################################################
# Pre-clear any globals to ensure the correct settings are applied.
###################################################################
unset XCPEDIR RPATH FSLDIR ANTSPATH AFNI_PATH C3D_PATH FREESURFER_HOME NUMOUT

###################################################################
# XCPEDIR stores a path to the top-level directory containing all
# of the ingredients necessary to configure and execute functional
# connectivity pipelines using the XCP Engine.
export XCPEDIR=${XCPEDIR}
###################################################################

###################################################################
# RPATH stores a path to the local installation of R. Dependencies
# may include:
#  * ANTsR
#  * pracma
#  * signal
#  * optparse
export RPATH=$(which R)
###################################################################

###################################################################
# FSLDIR stores a path to the local installation of FSL.
export FSLDIR=${FSLDIR}
###################################################################

###################################################################
# ANTSPATH stores a path to the local installation of ANTs.
export ANTSPATH=${ANTSPATH}
###################################################################

###################################################################
# AFNI_PATH stores a path to the local installation of AFNI.
export AFNI_PATH=${AFNI_PATH}
###################################################################

###################################################################
# C3D_PATH stores a path to the local installation of C3D.
export C3D_PATH=${C3D_PATH}
###################################################################

###################################################################
# JQ_PATH stores a path to the local installation of JQ.
export JQ_PATH=${JQ_PATH}
###################################################################

export FREESURFER_HOME=${FREESURFER_HOME}
source $FREESURFER_HOME/SetUpFreeSurfer.sh
###################################################################
# Outputs of modules may be prepended with an integer indicating
# their context in the pipeline. Set NUMOUT to 1 to enable this.
export NUMOUT=0
###################################################################
" >> ${XCPEDIR}/core/global


chmod 755 ${XCPEDIR}/core/global
