#!/usr/bin/env bash

###################################################################
#  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  #
###################################################################

###################################################################
# General module header
###################################################################
source ${XCPEDIR}/core/functions/library.sh

###################################################################
# Input job ID string, separated by '-e ',
# e.g., -e 435454 -e 435456 -e 453457
# sleep time is currently hard coded; ideally, it will instead be
# dependent on a module ping in the future
###################################################################
ids=$(echo ${@})
ids=${ids// /\|}
sleeptime=30

status=( $(matching "${ids}" $(qstat)) )
remain=${#status[@]}
time=$(date '+%H:%M:%S')
day=$(date '+%d %h %Y')
echo ""; echo ""; echo ""
echo "..."
echo "Waiting for ${remain} tasks"
echo "at ${time} on ${day}"
echo "..."
echo ""; echo ""; echo ""

while (( remain != 0 ))
   do
   sleep $sleeptime
   status=( $(matching "${ids}" $(qstat)) )
   remain=${#status[@]}
   [[ -z ${status} ]] && remain=0
   time=$(date '+%H:%M:%S')
   day=$(date '+%d %h %Y')
   echo ""; echo ""; echo ""
   echo "..."
   echo "Waiting for ${remain} tasks"
   echo "at ${time} on ${day}"
   echo "..."
   echo ""; echo ""; echo ""
done
