#!/usr/bin/env bash

###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################


###################################################################
# Check and log all XCP Engine dependencies
###################################################################





###################################################################
# Verify that all dependencies are installed.
# Obtain version information for all dependencies.
###################################################################
dc_FAIL=0
echo ""; echo "...Checking general dependencies..."
[[ -z $(afni -ver 2>/dev/null) ]] \
   && echo "   ::Dependencies check failed: AFNI" \
   && echo "   ::Please install AFNI and ensure that it has been added to your path" \
   && dc_FAIL=1 \
   || ver_AFNI=" * "$(afni -ver 2>/dev/null|head -n1) \
   && echo "${ver_AFNI}"
[[ -z $(command -v antsApplyTransforms 2>/dev/null) ]] \
   && echo "   ::Dependencies check failed: ANTs" \
   && echo "   ::Please install ANTs and ensure that it has been added to your path" \
   && dc_FAIL=1 \
   || ver_ANTS=" * Version ANTs "$(grep -i _GIT_VERSION_HASH $ANTSPATH/../ANTS-build/ProjectSourceVersionVars.cmake 2>/dev/null|cut -d'"' -f2) \
   && echo "${ver_ANTS}"
[[ -z $(command -v fslmaths 2>/dev/null) ]] \
   && echo "   ::Dependencies check failed: FSL" \
   && echo "   ::Please install FSL and ensure that it has been added to your path" \
   && dc_FAIL=1 \
   || ver_FSL=" * Version FSL "$(command -v fsl 2>/dev/null|rev|cut -d"/" -f3|rev) \
   && echo "${ver_FSL}"
[[ -z $(command -v c3d_affine_tool 2>/dev/null) ]] \
   && echo "   ::Dependencies check failed: ITK" \
   && echo "   ::Please install ITK and ensure that it has been added to your path" \
   && dc_FAIL=1 \
   || ver_ITK=" * Version ITK "$(itksnap --help 2>/dev/null|head -n2|tail -n1|rev|cut -d"/" -f 2|rev) \
   && echo "${ver_ITK}"
[[ -z $(R --version 2>/dev/null) ]] \
   && echo "   ::Dependencies check failed: R" \
   && echo "   ::Please install R and ensure that it has been added to your path" \
   && dc_FAIL=1 \
   || ver_R=" * "$(R --version|grep -i "R version") \
   && echo "${ver_R}"
[[ -z $(Rscript --version 2>&1 >/dev/null) ]] \
   && echo "   ::Dependencies check failed: Rscript" \
   && echo "   ::Please install Rscript and ensure that it has been added to your path" \
   && dc_FAIL=1 \
   || ver_RSCRIPT=" * "$(Rscript --version 2>&1 >/dev/null) \
   && echo "${ver_RSCRIPT}"
[[ ${mode} == c ]] \
   && [[ -z $(command -v qsub 2>/dev/null) ]] \
   && echo "   ::Dependencies check failed: grid engine" \
   && echo "   ::Please install a grid engine or use serial execution" \
   && dc_FAIL=1
RpackageChk=$(${XCPEDIR}/settings/checkRpackageDependencies.R)
echo "$RpackageChk"
[[ ! -z $(echo ${RpackageChk}|grep -i failed) ]] \
   && dc_FAIL=1
[[ ${dc_FAIL} == 1 ]] && echo "Aborting" && echo "" && exit 1
echo " * All general dependencies are present."
###################################################################
# Ensure environment variables are defined
###################################################################
echo "...Checking environment..."
[[ -z ${FSLDIR} ]] \
   && echo "   ::Environment check failed: FSLDIR not set" \
   && echo "   ::Please add FSLDIR to your environment" \
   && ec_FAIL=1
[[ -z ${ANTSPATH} ]] \
   && echo "   ::Environment check failed: ANTSPATH not set" \
   && echo "   ::Please add ANTSPATH to your environment" \
   && ec_FAIL=1
[[ -z ${XCPEDIR} ]] \
   && echo "   ::Environment check failed: XCPEDIR not set" \
   && echo "   ::Please add XCPEDIR to your environment" \
   && ec_FAIL=1
[[ ${ec_FAIL} == 1 ]] && echo "Aborting" && echo "" && exit 1
echo " * All environmental variables are defined."
