#!/usr/bin/env bash

###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# XCPEDIR stores a path to the top-level directory containing all
# of the ingredients necessary to configure and execute functional
# connectivity pipelines using the XCP Engine.
XCPEDIR=/data/joy/BBL/applications/xcpEngine
###################################################################

###################################################################
# RPATH stores a path to the local installation of R. Dependencies
# may include:
#  * ANTsR
#  * pracma
#  * igraph
#  * signal
#  * optparse
RPATH=/share/apps/R/R-3.1.1/bin/R
###################################################################

###################################################################
# FSLDIR stores a path to the local installation of FSL.
FSLDIR=/share/apps/fsl/5.0.8
###################################################################

###################################################################
# ANTSPATH stores a path to the local installation of ANTs.
ANTSPATH=/data/joy/BBL/applications/ants_20151007/bin/
###################################################################

###################################################################
# When subject-specific paths are generalised by utils/genpath,
# the value of KEEPNUM determines whether leading numeric values
# not matching subject identifiers are retained.
KEEPNUM=1
###################################################################

###################################################################
# The default value of the starting directory is stored here.
# Editing this will change where the XCP configuration script
# searches by default.
startdir=/data/joy/BBL/applications/xcpEngine
###################################################################

###################################################################
# Outputs of modules may be prepended with an integer indicating
# their context in the pipeline. Set NUMOUT to 1 to enable this.
NUMOUT=0
###################################################################

###################################################################
# Design files and analysis names will be timestamped to the
# minute if TIMESTAMP is set to 1.
TIMESTAMP=1
###################################################################

###################################################################
# The default pipeline is stored here. Edit this to change the
# default pipeline.
pipeline=
###################################################################
