#!/usr/bin/env bash

###################################################################
#  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  #
###################################################################

###################################################################
# Pre-clear any globals to ensure the correct settings are applied.
###################################################################
unset XCPEDIR RPATH FSLDIR ANTSPATH AFNI_PATH C3D_PATH NUMOUT

###################################################################
# XCPEDIR stores a path to the top-level directory containing all
# of the ingredients necessary to configure and execute functional
# connectivity pipelines using the XCP Engine.
export XCPEDIR=
###################################################################

###################################################################
# RPATH stores a path to the local installation of R. Dependencies
# may include:
#  * ANTsR
#  * pracma
#  * signal
#  * optparse
export RPATH=
###################################################################

###################################################################
# FSLDIR stores a path to the local installation of FSL.
export FSLDIR=
###################################################################

###################################################################
# ANTSPATH stores a path to the local installation of ANTs.
export ANTSPATH=
###################################################################

###################################################################
# AFNI_PATH stores a path to the local installation of AFNI.
export AFNI_PATH=
###################################################################

###################################################################
# C3D_PATH stores a path to the local installation of C3D.
export C3D_PATH=
###################################################################

###################################################################
# JQ_PATH stores a path to the local installation of JQ.
export JQ_PATH=
###################################################################

###################################################################
# Outputs of modules may be prepended with an integer indicating
# their context in the pipeline. Set NUMOUT to 1 to enable this.
export NUMOUT=
###################################################################

