#!/usr/bin/env bash


###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# Ensure that all image inputs are present
###################################################################

is_image(){
   (( $(${FSLDIR}/bin/imtest ${1}) == 1 ))
}

if ! is_image ${img[${subjidx}]} 
   then
   echo "::XCP-ERROR: Unable to locate functional timeseries."
   err=1
fi

if [[ ${space} == native ]]
   then
   if ! is_image ${struct[${subjidx}]}
      then
      echo "::XCP-ERROR: Unable to locate structural image."
      err=1
   fi
   if ! is_image ${template}
      then
      echo "::XCP-ERROR: Unable to locate template."
      err=1
   fi
   if ! is_image ${xfm_warp}
      then
      echo "::XCP-ERROR: Unable to locate warp."
      err=1
   fi
   if ! is_image ${ixfm_warp}
      then
      echo "::XCP-ERROR: Unable to locate inverse warp."
      err=1
   fi
fi

(( ${err} == 1 )) && exit 666
