#!/usr/bin/env bash


###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# GENERAL MODULE HEADER
###################################################################
export FSLOUTPUTTYPE=NIFTI_GZ
mod_out=$(cat ${XCPEDIR}/core/DESIGN_MODULE_OUTPUT)
usage_flag=0

###################################################################
# Read in:
#  * path to main design file
#  * current subject's identifier
#  * whether to explicitly trace all commands
# Trace status is, by default, set to 0 (no trace)
###################################################################
eval "echo -e \"$(<${mod_head})\""
trace=0
idx_offset=$(cat ${XCPEDIR}/core/SUBJECT_INDEX_OFFSET)
if (( $# < 2 ))
   then
   usage_flag=1
fi
while getopts "d:s:t:" OPTION
   do
   case $OPTION in
   d)
      design=${OPTARG}
      ;;
   s)
      subjidx=${OPTARG}
      ;;
   t)
      trace=${OPTARG}
      if (( ${trace} != 0 )) \
      && (( ${trace} != 1 )) \
      && (( ${trace} != 2 )) \
      && (( ${trace} != 3 ))
         then
         usage_flag=1
      fi
      ;;
   *)
      echo "Option not recognised: ${OPTION} ${OPTARG}"
      usage_flag=1
   esac
done
shift $((OPTIND-1))
###################################################################
# Ensure that the compulsory design and subject variables have
# been defined
###################################################################
[[ -z ${design} ]] && usage_flag=1
[[ -z ${subjidx} ]] && usage_flag=1
###################################################################
# Set trace status, if applicable
###################################################################
case ${trace} in
0)
   trace=0
   ;;
1)
   trace=1
   ;;
2)
   export trace=1
   ;;
3)
   set -x
   export ${SHELLOPTS}
   ;;
esac
###################################################################
# Usage and exit
###################################################################
if (( ${usage_flag} == 1 ))
   then
   cat ${XCPEDIR}/core/USAGE_LOCALISER
   exit 1
fi
###################################################################
# Initialise the module.
###################################################################
source $design
subjrow=$(( ${subjidx} - ${idx_offset} ))
subject=$(sed ${subjrow}'q;d' ${path_cohort})
