#!/usr/bin/env bash

###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# Update the quality file to add new variables defined in the
# course of processing.
###################################################################
rm -f ${quality[sub]}
qvars=$(join_by ',' ${qvars[@]})
qvals=$(join_by ',' ${qvals[@]})
echo ${qvars} >> ${quality[sub]}
echo ${qvals} >> ${quality[sub]}
