#!/usr/bin/env bash

###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# Verify that the compulsory argument "analytic cohort" is
# reasonably defined.
###################################################################
if [[ -z ${incohort} ]] || [[ ! -s ${incohort} ]]
   then
   echo \
"· [C]Missing or empty cohort file
· [C]Aborting"
   usage
   exit 3
fi
incohort=$(abspath ${incohort})





###################################################################
# Remove any duplications from the cohort file.
###################################################################
echo "· [C][${incohort}]"
${XCPEDIR}/utils/removeDuplicates.R -c ${incohort}
###################################################################
# Obtain the subject list.
###################################################################
idx_offset=$(cat ${XCPEDIR}/core/SUBJECT_INDEX_OFFSET)
mapfile -O ${idx_offset} cohort < ${incohort}
