#!/usr/bin/env bash

###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# Ensure that the compulsory argument "output path" is reasonably
# defined.
###################################################################
[[    -n ${out_super} ]]    &&    mkdir -p ${out_super}
if [[ -z ${out_super} ]]    ||    [[  ! -d ${out_super} ]]
   then
   echo \
"· [O]Missing or invalid output path
· [O]Aborting"
   usage
   exit 2
fi
out_super=$(abspath ${out_super})





###################################################################
# Set the group-level output directory.
###################################################################
echo "· [O][${out_super}]"
out_group=${out_super}/group
