#!/usr/bin/env bash

###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# Read the subject's log file to identify whether the subject
# should be skipped or flagged.
###################################################################
logfile=$1
subjid=$2


unset errortest qatest
if [[ -e ${logfile} ]]
   then
   error_test=$(grep -i XCP-ERROR ${logfile})
   qa_test=$(grep -i QA-EXCLUDE ${logfile})
fi

if [[ ! -z ${error_test} ]] || [[ ! -z ${qa_test} ]]
   then
   echo -e \
   "
   Skipping analysis for:
   * ${subjid}
   for the following reasons.
   ${error_test}
   ${qa_test}
   "
   exit 1
fi
