#!/usr/bin/env bash

###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# Verify that the compulsory argument "analytic cohort" is
# reasonably defined.
###################################################################
if [[ -z ${incohort} ]] || [[ ! -s ${incohort} ]]
   then
   echo \
"· [C]Missing or empty cohort file
· [C]Aborting"
   usage
   exit 3
fi
incohort=$(exec_fsl fsl_abspath ${incohort})





###################################################################
# Remove any duplications from the cohort file.
###################################################################
echo "· [C][${incohort}]"
${XCPEDIR}/utils/removeDuplicates.R \
   -c ${incohort} \
   -o ${out_generic}
###################################################################
# Obtain the subject list.
###################################################################
cohort=$(cat ${incohort} 2>/dev/null)
