#!/usr/bin/env bash

###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# Scan an index of subjects to determine whether any should be
# removed from the current analysis due to pipeline failure.
###################################################################
ERR_ROOT=${interm}/${analysis}-${xcp_date}

failure_chk() {
   local failures f fids
   failures=$(ls ${ERR_ROOT}-* 2>/dev/null)
   for f in ${failures}
      do
      f=${f//${ERR_ROOT}-/}
      fids="${fids} ${f}"
      unset ${cohort[f]}
   done
   if [[ -n ${fids} ]]
      then
      echo "
· [Module failure occurred in a number of subjects. They have been]
· [removed from further analysis.]"
      for f in ${fids}
         do
         echo "· · [${prefix[f]} removed from analysis]"
      done
   fi
   rm -f ${failures}
}

failure_chk
