#!/usr/bin/env bash

###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# Delocaliser: import all subject-level variables to the group
# level
###################################################################
idx_offset=$(cat ${XCPEDIR}/core/SUBJECT_INDEX_OFFSET)
mapfile -O ${idx_offset} cohort  < ${incohort}
###################################################################
# Get identifier variable names
###################################################################
subject_vars=${cohort[idx_offset]}
subject_vars=( ${subject_vars//,/ } )
for v in       "${subject_vars[@]}"
   do
   contains ${v} '^id[0-9]*$' \
   && id_vars=( "${id_vars[@]}" "${v}" )
done
ids[0]=$(join_by ',' ${id_vars[@]})
unset cohort[idx_offset]

###################################################################
# Remove any subjects that failed analysis
###################################################################
sub=$(( idx_offset + 1 ))
subject=${cohort[sub]}
subject_parse        ${subject} ${incohort}
source ${XCPEDIR}/core/defineDesign
source ${design[sub]}
source ${XCPEDIR}/core/validateSubjects

###################################################################
# Import subject-level variables from designs
###################################################################
for sub in ${!cohort[@]}
   do
   subject=${cohort[sub]}
   subject_parse        ${subject} ${incohort}
   source ${XCPEDIR}/core/defineDesign
   source ${design[sub]}
done

subjects=( ${!cohort[@]} )
