#!/usr/bin/env bash

###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# Function for eroding a mask while ensuring that some voxels
# remain in the mask.
###################################################################

###################################################################
# Constants
###################################################################
source ${XCPEDIR}/core/constants
source ${XCPEDIR}/core/functions/library.sh

###################################################################
# Usage function
###################################################################
Usage(){
cat << endstream
___________________________________________________________________


Usage: erodespare -i <input> -o <output> <options>

Compulsory arguments:
 -i : Input mask
      The 3D timeseries to which erosion is to be
      applied.

 -o : Output path
      The path to the file where the eroded mask will be
      written.

Optional arguments:
 -e : Erosion iterations [default 1]
      The maximum number of iterations of erosion to
      apply to the mask. If application of this many
      iterations of erosion results in a mask that is
      empty or fails to survive the minimum retention
      criterion, then progressively fewer iterations
      of erosion will be applied until the criterion is
      satisfied.

 -r : Minimum retention criterion [default 1 voxel]
      The minimum fraction of voxels that must be retained
      in the eroded mask for the mask to be accepted. A
      value of 1 accepts any non-empty mask.

 -t : Trace
      If this flag is set, then any commands called by the
      erodespare routine will be explicitly printed to the
      console or log.


endstream
}

###################################################################
# Define defaults
###################################################################
erode=1
###################################################################
# Parse arguments
###################################################################
while getopts "i:o:e:r:t" OPTION
   do
   case $OPTION in
   i)
      image=${OPTARG}
      ! is_image ${image} && Usage && exit
      ;;
   o)
      out=${OPTARG}
      ;;
   e)
      erode=${OPTARG}
      ! is+integer ${erode} && Usage && exit
      ;;
   r)
      minret=${OPTARG}
      ! is+numeric ${minret} && Usage && exit
      ;;
   t)
      set -x
      ;;
   *)
      echo "Option not recognised: ${OPTARG}"
      Usage
      exit
   esac
done
###################################################################
# Ensure that all compulsory arguments have been defined
###################################################################
[[ -z ${image} ]] && Usage && exit
[[ -z ${out} ]] && Usage && exit

exec_sys rm -f ${out}
masksize=( $(exec_fsl fslstats ${image} -V) )





if [[ -z ${minret} ]]
   then
   subroutine                 @u.1
   minret=$(arithmetic 1/${masksize[0]})
fi





while (( $(arithmetic ${erode}\>0) == 1 ))
   do
   subroutine                 @u.2
   exec_ants ImageMath 3 \
      ${out} \
      GE ${image} ${erode}
   ################################################################
   # If the erosion satisfies the minimum retention criterion,
   # break out of the loop. Otherwise, decrement the erosion
   # coefficient.
   ################################################################
   erodesize=( $(exec_fsl fslstats ${out} -V) )
   curret=$(arithmetic ${erodesize[0]}/${masksize[0]})
   if (( $(arithmetic ${curret}\>=${minret}) == 1))
      then
      subroutine              @u.3
      break
   else
      (( erode-- ))
      subroutine              @u.4a "[Erosion resulted in an empty mask.]"
      subroutine              @u.4b "[Decrementing coefficient to ${erode}]"
      exec_sys rm -f ${out}
   fi
done
###################################################################
# If erosion failed, then the output is identical to the input.
###################################################################
if ! is_image ${out}
   then
   subroutine                 @u.5  
   exec_sys ln -s ${image} ${out}
fi
###################################################################
# The output should be binary, but if it is not for some reason,
# then binarise it.
###################################################################
exec_fsl fslmaths ${out} -thr 0.5 -bin ${out}
