#!/usr/bin/env bash

###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# Transforms MNI coordinates into voxelwise coordinates
###################################################################
source ${XCPEDIR}/core/functions/verbose
source ${XCPEDIR}/core/functions/arithmetic

mni=( ${1//,/ } )
res=1
[[ $# -gt 1 ]] && res=$2

x=${mni[0]}
y=${mni[1]}
z=${mni[2]}

x=$(arithmetic ${x}*-1 + 90 )
y=$(arithmetic ${y} + 126 )
z=$(arithmetic ${z} + 72 )

if (( ${res} != 1 ))
   then
   x=$(arithmetic ${x}/${res})
   y=$(arithmetic ${y}/${res})
   z=$(arithmetic ${z}/${res})
fi

echo ${x},${y},${z}
