#!/usr/bin/env bash

###################################################################
#  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  #
###################################################################

###################################################################
# Utility for computing a distance matrix between each pair of
# nodes in a given parcellation or atlas
###################################################################

###################################################################
# Constants
###################################################################
source ${XCPEDIR}/core/constants
source ${XCPEDIR}/core/functions/library.sh

###################################################################
# Usage function
###################################################################
Usage(){
cat << endstream
___________________________________________________________________


Usage: `basename $0` -a <atlas> -o <output> <options>

Compulsory arguments:
 -a : Atlas
      The atlas that defines regions or groupings of voxels
      for distance computation. This should be a NIfTI image; use
      distmat.R instead for spatial coordinate libraries.

 -o : Output matrix
      The path where the distance matrix is to be written

Optional arguments:
 -i : Intermediate output path
      A path where intermediate files are to be written

endstream
}





###################################################################
# Parse arguments
###################################################################
while getopts "a:o:i:" OPTION
   do
   case $OPTION in
   a)
      atlas=${OPTARG}
      ! is_image ${atlas} && Usage && exit
      ;;
   o)
      opath=${OPTARG}
      ;;
   i)
      intermediate=${OPTARG}-roi2distmat
      ;;
   *)
      echo "Option not recognised: ${OPTARG}"
      Usage
      exit
      ;;
   esac
done
###################################################################
# Ensure that all compulsory arguments have been defined
###################################################################
[[ -z ${atlas} ]]             && Usage && exit
[[ -z ${opath} ]]             && Usage && exit
[[ -z ${intermediate} ]]      && intermediate=${output_root}





###################################################################
# Obtain the centres of mass for each network node.
###################################################################
subroutine                    @u.1  Identifying nodal centres of mass
exec_sys rm -f ${intermediate}-cmass.sclib
exec_xcp cmass.R                                   \
   -r    ${atlas}                                  \
   >>    ${intermediate}-cmass.sclib





###################################################################
# Build the edgewise distance matrix.
###################################################################
subroutine                    @u.2  Constructing distance matrix
exec_sys rm -f ${opath}
exec_xcp distmat.R                                 \
   -c    ${intermediate}-cmass.sclib               \
   >>    ${opath}
