#!/usr/bin/env bash

###################################################################
#  ✡✡ ✡✡✡✡ ✡✡✡✡✡✡✡✡✡ ✡✡✡✡✡✡✡✡✡✡✡✡✡ ✡✡✡✡✡✡✡✡✡✡✡✡✡ ✡✡✡✡✡✡✡✡ ✡✡✡✡ ✡✡ #
###################################################################

###################################################################
# Function to calculate sulcal depth
###################################################################

###################################################################
# Constants
###################################################################
source ${XCPEDIR}/core/constants
source ${XCPEDIR}/core/functions/library.sh

###################################################################
# Usage function
###################################################################
Usage(){
cat << endstream
___________________________________________________________________


Usage: `basename $0` -l <rawJlfLabelImage> -b <BE Map> -o <outDistanceImage> <options>

Compulsory arguments:
 -l : rawJlfLabelImage
      The output label image from the JLF pipeline, without any intersections applied

 -b : BE Map
      A binary image which was used to perform brain extraction on the raw T1 image 

 -s : Segmentation image
      The  6 class tissue segmentation from the output of ANTsCT

 -o : outDistanceImage
      The file where the output distane image will be written to.

Optional arguments:
 -i : Intermediate output path
      Path for input and output of temporary files (intermediates)
      (default: current directory)

endstream
}

###################################################################
# Define defaults
###################################################################
[[ -z ${intermediate} ]] && intermediate=$(pwd)/layerLabels~TEMP~

###################################################################
# Parse arguments
###################################################################
while getopts "l:o:b:i:s:" OPTION
   do
   case $OPTION in
   l)
      label=${OPTARG}
      ! is_image ${label} && Usage && exit
      ;;
   o)
      out=${OPTARG}
      ;;
   i)
      intermediate=${OPTARG}-sulcalDepth
      ;;
   s)
      segImage=${OPTARG}
      ! is_image ${segImage} && Usage && exit
      ;;
   b)
      beImage=${OPTARG}
      ! is_image ${beImage} && Usage && exit
      ;;
   *)
      echo "Option not recognised: ${OPTARG}"
      Usage
      exit
   esac
done

###################################################################
# Ensure that all compulsory arguments have been defined
###################################################################
[[ -z ${label} ]] && Usage && exit
[[ -z ${beImage} ]] && Usage && exit
[[ -z ${out}   ]] && Usage && exit

###################################################################
# Declare any static variables
###################################################################
rmIsolVals="23,31,33,36,42,44,47,49,51,53,55,57,59,61,63,66,68,76,100,102,104,106,108,110,112,114,116,118,120,122,124,126,128,130,132,134,136,138,140,142,144,146,148,150,152,154,156,158,160,162,164,166,168,170,172,174,176,178,180,182,184,186,188,190,192,194,196,198,200,202,204,206"
lmIsolVals="30,32,34,37,43,45,48,50,52,54,56,58,60,62,64,65,67,75,101,103,105,107,109,111,113,115,117,119,121,123,125,127,129,131,133,135,137,139,141,143,145,147,149,151,153,155,157,159,161,163,165,167,169,171,173,175,177,179,181,183,185,187,189,191,193,195,197,199,201,203,205,207"

###################################################################
# Create our hemisphere specific dura mask
# Start with the right hemisphere
###################################################################
subroutine                    @u.1
exec_xcp val2mask.R -i ${label} -v ${rmIsolVals} -o ${intermediate}/rightHemi.nii.gz
exec_ants ImageMath 3 ${intermediate}/rightHemiDistance.nii.gz MaurerDistance ${intermediate}/rightHemi.nii.gz 1
exec_fsl fslmaths ${intermediate}/rightHemiDistance.nii.gz -uthr 2 -bin ${intermediate}/rightHemiDistanceBin.nii.gz
exec_fsl fslmaths ${intermediate}/rightHemiDistanceBin.nii.gz -add ${intermediate}/rightHemi.nii.gz -bin ${intermediate}/rightHemiMask.nii.gz
exec_fsl fslmaths ${intermediate}/rightHemiMask.nii.gz -ero ${intermediate}/rightHemiMaskEro.nii.gz
exec_fsl fslmaths ${intermediate}/rightHemiMask.nii.gz -sub ${intermediate}/rightHemiMaskEro.nii.gz ${intermediate}/DuraEstimateRight.nii.gz

###################################################################
# Now onto the left hemisphere
###################################################################
subroutine                    @u.2
exec_xcp val2mask.R -i ${label} -v ${lmIsolVals} -o ${intermediate}/leftHemi.nii.gz
exec_ants ImageMath 3 ${intermediate}/leftHemiDistance.nii.gz MaurerDistance ${intermediate}/leftHemi.nii.gz 1
exec_fsl fslmaths ${intermediate}/leftHemiDistance.nii.gz -uthr 2 -bin ${intermediate}/leftHemiDistanceBin.nii.gz 
exec_fsl fslmaths ${intermediate}/leftHemiDistanceBin.nii.gz -add ${intermediate}/leftHemi.nii.gz -bin ${intermediate}/leftHemiMask.nii.gz
exec_fsl fslmaths ${intermediate}/leftHemiMask.nii.gz -ero ${intermediate}/leftHemiMaskEro.nii.gz
exec_fsl fslmaths ${intermediate}/leftHemiMask.nii.gz -sub ${intermediate}/leftHemiMaskEro.nii.gz ${intermediate}/DuraEstimateLeft.nii.gz

###################################################################
# Now combine the dura hemisphere maps and calculate distance from the dura
###################################################################
subroutine                    @u.3
exec_fsl fslmaths ${intermediate}/DuraEstimateLeft.nii.gz -add ${intermediate}/DuraEstimateRight.nii.gz -bin ${intermediate}/Dura.nii.gz
exec_ants ImageMath 3 ${intermediate}/DistanceFromDura.nii.gz MaurerDistance ${intermediate}/Dura.nii.gz 1

###################################################################
# Now produce our GM edge image
###################################################################
subroutine                    @u.4
exec_afni 3dresample -dxyz .25 .25 .25 -inset ${segImage} -prefix ${intermediate}/Upsample.nii.gz
exec_fsl fslmaths ${intermediate}/Upsample.nii.gz -thr 2 -uthr 2 -bin -edge -bin ${intermediate}/GmEdge.nii.gz
exec_ants antsApplyTransforms -e 3 -d 3 -i ${intermediate}/GmEdge.nii.gz -o ${intermediate}/GmEdgeDS.nii.gz -r ${segImage} -n Gaussian
exec_fsl fslmaths ${intermediate}/GmEdgeDS.nii.gz -thr .05 -bin ${intermediate}/GmEdgeDSBin.nii.gz
exec_fsl fslmaths ${intermediate}/DistanceFromDura.nii.gz -mul ${intermediate}/GmEdgeDSBin.nii.gz ${out}
