#!/usr/bin/env bash

###################################################################
#  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  ☭  #
###################################################################

###################################################################
# Transforms voxelwise coordinates into MNI coordinates
###################################################################
source ${XCPEDIR}/core/functions/verbose
source ${XCPEDIR}/core/functions/arithmetic

vox=( ${1//,/ } )
res=1
[[ $# -gt 1 ]] && res=$2

x=${vox[0]}
y=${vox[1]}
z=${vox[2]}

if (( ${res} != 1 ))
   then
   x=$(arithmetic ${x}*${res})
   y=$(arithmetic ${y}*${res})
   z=$(arithmetic ${z}*${res})
fi

x=$(arithmetic ${x} - 90)
x=$(arithmetic ${x}*-1)
y=$(arithmetic ${y} - 126)
z=$(arithmetic ${z} - 72)

echo ${x},${y},${z}
